name: neuebrandenbook_catalogue
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  quick_actions: ^1.1.0
  share_plus: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/data/
  - assets/images/Author-Profile-Pictures/
  - assets/images/Book-Covers/
